using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Data.Entity;

namespace Antykwariat.Models
{
    public class SampleData : DropCreateDatabaseIfModelChanges<AntykwariatEntities>
    {
        protected override void Seed(AntykwariatEntities context)
        {
            var gatunki = new List<Gatunek>
            {
                new Gatunek { Nazwa = "Rock" },
                new Gatunek { Nazwa = "Jazz" },
                new Gatunek { Nazwa = "Metal" },
                new Gatunek { Nazwa = "Alternative" },
                new Gatunek { Nazwa = "Disco" },
                new Gatunek { Nazwa = "Blues" },
                new Gatunek { Nazwa = "Latin" },
                new Gatunek { Nazwa = "Reggae" },
                new Gatunek { Nazwa = "Pop" },
                new Gatunek { Nazwa = "Classical" }
            };

            var autorzy = new List<Autor>
            {
                new Autor { Nazwa = "Aaron Copland & London Symphony Orchestra" },
                new Autor { Nazwa = "Aaron Goldberg" },
                new Autor { Nazwa = "AC/DC" },
                new Autor { Nazwa = "Accept" },
                new Autor { Nazwa = "Adrian Leaper & Doreen de Feis" },
                new Autor { Nazwa = "Aerosmith" },
                new Autor { Nazwa = "Aisha Duo" },
                new Autor { Nazwa = "Alanis Morissette" },
                new Autor { Nazwa = "Alberto Turco & Nova Schola Gregoriana" },
                new Autor { Nazwa = "Alice In Chains" },
                new Autor { Nazwa = "Amy Winehouse" },
                new Autor { Nazwa = "Anita Ward" },
                new Autor { Nazwa = "Antônio Carlos Jobim" },
                new Autor { Nazwa = "Apocalyptica" },
                new Autor { Nazwa = "Audioslave" },
                new Autor { Nazwa = "Barry Wordsworth & BBC Concert Orchestra" },
                new Autor { Nazwa = "Berliner Philharmoniker & Hans Rosbaud" },
                new Autor { Nazwa = "Berliner Philharmoniker & Herbert Von Karajan" },
                new Autor { Nazwa = "Billy Cobham" },
                new Autor { Nazwa = "Black Label Society" },
                new Autor { Nazwa = "Black Sabbath" },
                new Autor { Nazwa = "Boston Symphony Orchestra & Seiji Ozawa" },
                new Autor { Nazwa = "Britten Sinfonia, Ivor Bolton & Lesley Garrett" },
                new Autor { Nazwa = "Bruce Dickinson" },
                new Autor { Nazwa = "Buddy Guy" },
                new Autor { Nazwa = "Caetano Veloso" },
                new Autor { Nazwa = "Cake" },
                new Autor { Nazwa = "Calexico" },
                new Autor { Nazwa = "Cássia Eller" },
                new Autor { Nazwa = "Chic" },
                new Autor { Nazwa = "Chicago Symphony Orchestra & Fritz Reiner" },
                new Autor { Nazwa = "Chico Buarque" },
                new Autor { Nazwa = "Chico Science & Nação Zumbi" },
                new Autor { Nazwa = "Choir Of Westminster Abbey & Simon Preston" },
                new Autor { Nazwa = "Chris Cornell" },
                new Autor { Nazwa = "Christopher O'Riley" },
                new Autor { Nazwa = "Cidade Negra" },
                new Autor { Nazwa = "Cláudio Zoli" },
                new Autor { Nazwa = "Creedence Clearwater Revival" },
                new Autor { Nazwa = "David Coverdale" },
                new Autor { Nazwa = "Deep Purple" },
                new Autor { Nazwa = "Dennis Chambers" },
                new Autor { Nazwa = "Djavan" },
                new Autor { Nazwa = "Donna Summer" },
                new Autor { Nazwa = "Dread Zeppelin" },
                new Autor { Nazwa = "Ed Motta" },
                new Autor { Nazwa = "Edo de Waart & San Francisco Symphony" },
                new Autor { Nazwa = "Elis Regina" },
                new Autor { Nazwa = "English Concert & Trevor Pinnock" },
                new Autor { Nazwa = "Eric Clapton" },
                new Autor { Nazwa = "Eugene Ormandy" },
                new Autor { Nazwa = "Faith No More" },
                new Autor { Nazwa = "Falamansa" },
                new Autor { Nazwa = "Foo Fighters" },
                new Autor { Nazwa = "Frank Zappa & Captain Beefheart" },
                new Autor { Nazwa = "Fretwork" },
                new Autor { Nazwa = "Funk Como Le Gusta" },
                new Autor { Nazwa = "Gerald Moore" },
                new Autor { Nazwa = "Gilberto Gil" },
                new Autor { Nazwa = "Godsmack" },
                new Autor { Nazwa = "Gonzaguinha" },
                new Autor { Nazwa = "Göteborgs Symfoniker & Neeme Järvi" },
                new Autor { Nazwa = "Guns N' Roses" },
                new Autor { Nazwa = "Gustav Mahler" },
                new Autor { Nazwa = "Incognito" },
                new Autor { Nazwa = "Iron Maiden" },
                new Autor { Nazwa = "James Levine" },
                new Autor { Nazwa = "Jamiroquai" },
                new Autor { Nazwa = "Jimi Hendrix" },
                new Autor { Nazwa = "Joe Satriani" },
                new Autor { Nazwa = "Jorge Ben" },
                new Autor { Nazwa = "Jota Quest" },
                new Autor { Nazwa = "Judas Priest" },
                new Autor { Nazwa = "Julian Bream" },
                new Autor { Nazwa = "Kent Nagano and Orchestre de l'Opéra de Lyon" },
                new Autor { Nazwa = "Kiss" },
                new Autor { Nazwa = "Led Zeppelin" },
                new Autor { Nazwa = "Legião Urbana" },
                new Autor { Nazwa = "Lenny Kravitz" },
                new Autor { Nazwa = "Les Arts Florissants & William Christie" },
                new Autor { Nazwa = "London Symphony Orchestra & Sir Charles Mackerras" },
                new Autor { Nazwa = "Luciana Souza/Romero Lubambo" },
                new Autor { Nazwa = "Lulu Santos" },
                new Autor { Nazwa = "Marcos Valle" },
                new Autor { Nazwa = "Marillion" },
                new Autor { Nazwa = "Marisa Monte" },
                new Autor { Nazwa = "Martin Roscoe" },
                new Autor { Nazwa = "Maurizio Pollini" },
                new Autor { Nazwa = "Mela Tenenbaum, Pro Musica Prague & Richard Kapp" },
                new Autor { Nazwa = "Men At Work" },
                new Autor { Nazwa = "Metallica" },
                new Autor { Nazwa = "Michael Tilson Thomas & San Francisco Symphony" },
                new Autor { Nazwa = "Miles Davis" },
                new Autor { Nazwa = "Milton Nascimento" },
                new Autor { Nazwa = "Mötley Crüe" },
                new Autor { Nazwa = "Motörhead" },
                new Autor { Nazwa = "Nash Ensemble" },
                new Autor { Nazwa = "Nicolaus Esterhazy Sinfonia" },
                new Autor { Nazwa = "Nirvana" },
                new Autor { Nazwa = "O Terço" },
                new Autor { Nazwa = "Olodum" },
                new Autor { Nazwa = "Orchestra of The Age of Enlightenment" },
                new Autor { Nazwa = "Os Paralamas Do Sucesso" },
                new Autor { Nazwa = "Ozzy Osbourne" },
                new Autor { Nazwa = "Page & Plant" },
                new Autor { Nazwa = "Paul D'Ianno" },
                new Autor { Nazwa = "Pearl Jam" },
                new Autor { Nazwa = "Pink Floyd" },
                new Autor { Nazwa = "Queen" },
                new Autor { Nazwa = "R.E.M." },
                new Autor { Nazwa = "Raul Seixas" },
                new Autor { Nazwa = "Red Hot Chili Peppers" },
                new Autor { Nazwa = "Roger Norrington, London Classical Players" },
                new Autor { Nazwa = "Royal Philharmonic Orchestra & Sir Thomas Beecham" },
                new Autor { Nazwa = "Rush" },
                new Autor { Nazwa = "Santana" },
                new Autor { Nazwa = "Scholars Baroque Ensemble" },
                new Autor { Nazwa = "Scorpions" },
                new Autor { Nazwa = "Sergei Prokofiev & Yuri Temirkanov" },
                new Autor { Nazwa = "Sir Georg Solti & Wiener Philharmoniker" },
                new Autor { Nazwa = "Skank" },
                new Autor { Nazwa = "Soundgarden" },
                new Autor { Nazwa = "Spyro Gyra" },
                new Autor { Nazwa = "Stevie Ray Vaughan & Double Trouble" },
                new Autor { Nazwa = "Stone Temple Pilots" },
                new Autor { Nazwa = "System Of A Down" },
                new Autor { Nazwa = "Temple of the Dog" },
                new Autor { Nazwa = "Terry Bozzio, Tony Levin & Steve Stevens" },
                new Autor { Nazwa = "The 12 Cellists of The Berlin Philharmonic" },
                new Autor { Nazwa = "The Black Crowes" },
                new Autor { Nazwa = "The Cult" },
                new Autor { Nazwa = "The Doors" },
                new Autor { Nazwa = "The King's Singers" },
                new Autor { Nazwa = "The Police" },
                new Autor { Nazwa = "The Posies" },
                new Autor { Nazwa = "The Rolling Stones" },
                new Autor { Nazwa = "The Who" },
                new Autor { Nazwa = "Tim Maia" },
                new Autor { Nazwa = "Ton Koopman" },
                new Autor { Nazwa = "U2" },
                new Autor { Nazwa = "UB40" },
                new Autor { Nazwa = "Van Halen" },
                new Autor { Nazwa = "Various Artists" },
                new Autor { Nazwa = "Velvet Revolver" },
                new Autor { Nazwa = "Vinícius De Moraes" },
                new Autor { Nazwa = "Wilhelm Kempff" },
                new Autor { Nazwa = "Yehudi Menuhin" },
                new Autor { Nazwa = "Yo-Yo Ma" },
                new Autor { Nazwa = "Zeca Pagodinho" }
            };

            new List<Ksiazka>
            {
                new Ksiazka { Tytul = "The Best Of Men At Work", Gatunek = gatunki.Single(g => g.Nazwa == "Rock"), Cena = 8.99M, Autor = autorzy.Single(a => a.Nazwa == "Men At Work"), Okladka = "/Content/Images/placeholder.gif" },
                new Ksiazka { Tytul = "A Copland Celebration, Vol. I", Gatunek = gatunki.Single(g => g.Nazwa == "Classical"), Cena = 8.99M, Autor = autorzy.Single(a => a.Nazwa == "Aaron Copland & London Symphony Orchestra"), Okladka = "/Content/Images/placeholder.gif" },
                new Ksiazka { Tytul = "Worlds", Gatunek = gatunki.Single(g => g.Nazwa == "Jazz"), Cena = 8.99M, Autor = autorzy.Single(a => a.Nazwa == "Aaron Goldberg"), Okladka = "/Content/Images/placeholder.gif" },
                new Ksiazka { Tytul = "For Those About To Rock We Salute You", Gatunek = gatunki.Single(g => g.Nazwa == "Rock"), Cena = 8.99M, Autor = autorzy.Single(a => a.Nazwa == "AC/DC"), Okladka = "/Content/Images/placeholder.gif" },
                new Ksiazka { Tytul = "Let There Be Rock", Gatunek = gatunki.Single(g => g.Nazwa == "Rock"), Cena = 8.99M, Autor = autorzy.Single(a => a.Nazwa == "AC/DC"), Okladka = "/Content/Images/placeholder.gif" },
                new Ksiazka { Tytul = "Balls to the Wall", Gatunek = gatunki.Single(g => g.Nazwa == "Rock"), Cena = 8.99M, Autor = autorzy.Single(a => a.Nazwa == "Accept"), Okladka = "/Content/Images/placeholder.gif" },
                new Ksiazka { Tytul = "Restless and Wild", Gatunek = gatunki.Single(g => g.Nazwa == "Rock"), Cena = 8.99M, Autor = autorzy.Single(a => a.Nazwa == "Accept"), Okladka = "/Content/Images/placeholder.gif" },
                new Ksiazka { Tytul = "Górecki: Symphony No. 3", Gatunek = gatunki.Single(g => g.Nazwa == "Classical"), Cena = 8.99M, Autor = autorzy.Single(a => a.Nazwa == "Adrian Leaper & Doreen de Feis"), Okladka = "/Content/Images/placeholder.gif" },
                new Ksiazka { Tytul = "Big Ones", Gatunek = gatunki.Single(g => g.Nazwa == "Rock"), Cena = 8.99M, Autor = autorzy.Single(a => a.Nazwa == "Aerosmith"), Okladka = "/Content/Images/placeholder.gif" },
                new Ksiazka { Tytul = "Quiet Songs", Gatunek = gatunki.Single(g => g.Nazwa == "Jazz"), Cena = 8.99M, Autor = autorzy.Single(a => a.Nazwa == "Aisha Duo"), Okladka = "/Content/Images/placeholder.gif" },
                new Ksiazka { Tytul = "Jagged Little Pill", Gatunek = gatunki.Single(g => g.Nazwa == "Rock"), Cena = 8.99M, Autor = autorzy.Single(a => a.Nazwa == "Alanis Morissette"), Okladka = "/Content/Images/placeholder.gif" },
                new Ksiazka { Tytul = "Facelift", Gatunek = gatunki.Single(g => g.Nazwa == "Rock"), Cena = 8.99M, Autor = autorzy.Single(a => a.Nazwa == "Alice In Chains"), Okladka = "/Content/Images/placeholder.gif" },
                new Ksiazka { Tytul = "Frank", Gatunek = gatunki.Single(g => g.Nazwa == "Pop"), Cena = 8.99M, Autor = autorzy.Single(a => a.Nazwa == "Amy Winehouse"), Okladka = "/Content/Images/placeholder.gif" },
                new Ksiazka { Tytul = "Ring My Bell", Gatunek = gatunki.Single(g => g.Nazwa == "Disco"), Cena = 8.99M, Autor = autorzy.Single(a => a.Nazwa == "Anita Ward"), Okladka = "/Content/Images/placeholder.gif" },
                new Ksiazka { Tytul = "Chill: Brazil (Disc 2)", Gatunek = gatunki.Single(g => g.Nazwa == "Latin"), Cena = 8.99M, Autor = autorzy.Single(a => a.Nazwa == "Antônio Carlos Jobim"), Okladka = "/Content/Images/placeholder.gif" },
                new Ksiazka { Tytul = "Warner 25 Anos", Gatunek = gatunki.Single(g => g.Nazwa == "Jazz"), Cena = 8.99M, Autor = autorzy.Single(a => a.Nazwa == "Antônio Carlos Jobim"), Okladka = "/Content/Images/placeholder.gif" },
                new Ksiazka { Tytul = "Plays Metallica By Four Cellos", Gatunek = gatunki.Single(g => g.Nazwa == "Metal"), Cena = 8.99M, Autor = autorzy.Single(a => a.Nazwa == "Apocalyptica"), Okladka = "/Content/Images/placeholder.gif" },
                new Ksiazka { Tytul = "Revelations", Gatunek = gatunki.Single(g => g.Nazwa == "Alternative"), Cena = 8.99M, Autor = autorzy.Single(a => a.Nazwa == "Audioslave"), Okladka = "/Content/Images/placeholder.gif" },
                new Ksiazka { Tytul = "Audioslave", Gatunek = gatunki.Single(g => g.Nazwa == "Rock"), Cena = 8.99M, Autor = autorzy.Single(a => a.Nazwa == "Audioslave"), Okladka = "/Content/Images/placeholder.gif" },
                new Ksiazka { Tytul = "The Last Night of the Proms", Gatunek = gatunki.Single(g => g.Nazwa == "Classical"), Cena = 8.99M, Autor = autorzy.Single(a => a.Nazwa == "Barry Wordsworth & BBC Concert Orchestra"), Okladka = "/Content/Images/placeholder.gif" },
                new Ksiazka { Tytul = "Sibelius: Finlandia", Gatunek = gatunki.Single(g => g.Nazwa == "Classical"), Cena = 8.99M, Autor = autorzy.Single(a => a.Nazwa == "Berliner Philharmoniker & Hans Rosbaud"), Okladka = "/Content/Images/placeholder.gif" },
                new Ksiazka { Tytul = "Mozart: Symphonies Nos. 40 & 41", Gatunek = gatunki.Single(g => g.Nazwa == "Classical"), Cena = 8.99M, Autor = autorzy.Single(a => a.Nazwa == "Berliner Philharmoniker & Herbert Von Karajan"), Okladka = "/Content/Images/placeholder.gif" },
                new Ksiazka { Tytul = "The Best Of Billy Cobham", Gatunek = gatunki.Single(g => g.Nazwa == "Jazz"), Cena = 8.99M, Autor = autorzy.Single(a => a.Nazwa == "Billy Cobham"), Okladka = "/Content/Images/placeholder.gif" },
                new Ksiazka { Tytul = "Alcohol Fueled Brewtality Live! [Disc 1]", Gatunek = gatunki.Single(g => g.Nazwa == "Metal"), Cena = 8.99M, Autor = autorzy.Single(a => a.Nazwa == "Black Label Society"), Okladka = "/Content/Images/placeholder.gif" },
                new Ksiazka { Tytul = "Alcohol Fueled Brewtality Live! [Disc 2]", Gatunek = gatunki.Single(g => g.Nazwa == "Metal"), Cena = 8.99M, Autor = autorzy.Single(a => a.Nazwa == "Black Label Society"), Okladka = "/Content/Images/placeholder.gif" },
                new Ksiazka { Tytul = "Black Sabbath Vol. 4 (Remaster)", Gatunek = gatunki.Single(g => g.Nazwa == "Metal"), Cena = 8.99M, Autor = autorzy.Single(a => a.Nazwa == "Black Sabbath"), Okladka = "/Content/Images/placeholder.gif" },
                new Ksiazka { Tytul = "Black Sabbath", Gatunek = gatunki.Single(g => g.Nazwa == "Metal"), Cena = 8.99M, Autor = autorzy.Single(a => a.Nazwa == "Black Sabbath"), Okladka = "/Content/Images/placeholder.gif" },
                new Ksiazka { Tytul = "Carmina Burana", Gatunek = gatunki.Single(g => g.Nazwa == "Classical"), Cena = 8.99M, Autor = autorzy.Single(a => a.Nazwa == "Boston Symphony Orchestra & Seiji Ozawa"), Okladka = "/Content/Images/placeholder.gif" },
                new Ksiazka { Tytul = "A Soprano Inspired", Gatunek = gatunki.Single(g => g.Nazwa == "Classical"), Cena = 8.99M, Autor = autorzy.Single(a => a.Nazwa == "Britten Sinfonia, Ivor Bolton & Lesley Garrett"), Okladka = "/Content/Images/placeholder.gif" },
                new Ksiazka { Tytul = "Chemical Wedding", Gatunek = gatunki.Single(g => g.Nazwa == "Metal"), Cena = 8.99M, Autor = autorzy.Single(a => a.Nazwa == "Bruce Dickinson"), Okladka = "/Content/Images/placeholder.gif" },
                new Ksiazka { Tytul = "Prenda Minha", Gatunek = gatunki.Single(g => g.Nazwa == "Latin"), Cena = 8.99M, Autor = autorzy.Single(a => a.Nazwa == "Caetano Veloso"), Okladka = "/Content/Images/placeholder.gif" },
                new Ksiazka { Tytul = "Sozinho Remix Ao Vivo", Gatunek = gatunki.Single(g => g.Nazwa == "Latin"), Cena = 8.99M, Autor = autorzy.Single(a => a.Nazwa == "Caetano Veloso"), Okladka = "/Content/Images/placeholder.gif" },
                new Ksiazka { Tytul = "Cake: B-Sides and Rarities", Gatunek = gatunki.Single(g => g.Nazwa == "Alternative"), Cena = 8.99M, Autor = autorzy.Single(a => a.Nazwa == "Cake"), Okladka = "/Content/Images/placeholder.gif" },
                new Ksiazka { Tytul = "Carried to Dust (Bonus Track Version)", Gatunek = gatunki.Single(g => g.Nazwa == "Alternative"), Cena = 8.99M, Autor = autorzy.Single(a => a.Nazwa == "Calexico"), Okladka = "/Content/Images/placeholder.gif" },
                new Ksiazka { Tytul = "Cássia Eller - Sem Limite [Disc 1]", Gatunek = gatunki.Single(g => g.Nazwa == "Latin"), Cena = 8.99M, Autor = autorzy.Single(a => a.Nazwa == "Cássia Eller"), Okladka = "/Content/Images/placeholder.gif" },
                new Ksiazka { Tytul = "Le Freak", Gatunek = gatunki.Single(g => g.Nazwa == "Disco"), Cena = 8.99M, Autor = autorzy.Single(a => a.Nazwa == "Chic"), Okladka = "/Content/Images/placeholder.gif" },
                new Ksiazka { Tytul = "Scheherazade", Gatunek = gatunki.Single(g => g.Nazwa == "Classical"), Cena = 8.99M, Autor = autorzy.Single(a => a.Nazwa == "Chicago Symphony Orchestra & Fritz Reiner"), Okladka = "/Content/Images/placeholder.gif" },
                new Ksiazka { Tytul = "Minha Historia", Gatunek = gatunki.Single(g => g.Nazwa == "Latin"), Cena = 8.99M, Autor = autorzy.Single(a => a.Nazwa == "Chico Buarque"), Okladka = "/Content/Images/placeholder.gif" },
                new Ksiazka { Tytul = "Afrociberdelia", Gatunek = gatunki.Single(g => g.Nazwa == "Latin"), Cena = 8.99M, Autor = autorzy.Single(a => a.Nazwa == "Chico Science & Nação Zumbi"), Okladka = "/Content/Images/placeholder.gif" },
                new Ksiazka { Tytul = "Da Lama Ao Caos", Gatunek = gatunki.Single(g => g.Nazwa == "Latin"), Cena = 8.99M, Autor = autorzy.Single(a => a.Nazwa == "Chico Science & Nação Zumbi"), Okladka = "/Content/Images/placeholder.gif" },
                new Ksiazka { Tytul = "Carry On", Gatunek = gatunki.Single(g => g.Nazwa == "Alternative"), Cena = 8.99M, Autor = autorzy.Single(a => a.Nazwa == "Chris Cornell"), Okladka = "/Content/Images/placeholder.gif" },
                new Ksiazka { Tytul = "SCRIABIN: Vers la flamme", Gatunek = gatunki.Single(g => g.Nazwa == "Classical"), Cena = 8.99M, Autor = autorzy.Single(a => a.Nazwa == "Christopher O'Riley"), Okladka = "/Content/Images/placeholder.gif" },
                new Ksiazka { Tytul = "Acústico MTV [Live]", Gatunek = gatunki.Single(g => g.Nazwa == "Reggae"), Cena = 8.99M, Autor = autorzy.Single(a => a.Nazwa == "Cidade Negra"), Okladka = "/Content/Images/placeholder.gif" },
                new Ksiazka { Tytul = "Cidade Negra - Hits", Gatunek = gatunki.Single(g => g.Nazwa == "Reggae"), Cena = 8.99M, Autor = autorzy.Single(a => a.Nazwa == "Cidade Negra"), Okladka = "/Content/Images/placeholder.gif" },
                new Ksiazka { Tytul = "Na Pista", Gatunek = gatunki.Single(g => g.Nazwa == "Latin"), Cena = 8.99M, Autor = autorzy.Single(a => a.Nazwa == "Cláudio Zoli"), Okladka = "/Content/Images/placeholder.gif" },
                new Ksiazka { Tytul = "Chronicle, Vol. 1", Gatunek = gatunki.Single(g => g.Nazwa == "Rock"), Cena = 8.99M, Autor = autorzy.Single(a => a.Nazwa == "Creedence Clearwater Revival"), Okladka = "/Content/Images/placeholder.gif" },
                new Ksiazka { Tytul = "Chronicle, Vol. 2", Gatunek = gatunki.Single(g => g.Nazwa == "Rock"), Cena = 8.99M, Autor = autorzy.Single(a => a.Nazwa == "Creedence Clearwater Revival"), Okladka = "/Content/Images/placeholder.gif" },
                new Ksiazka { Tytul = "Into The Light", Gatunek = gatunki.Single(g => g.Nazwa == "Rock"), Cena = 8.99M, Autor = autorzy.Single(a => a.Nazwa == "David Coverdale"), Okladka = "/Content/Images/placeholder.gif" },
                new Ksiazka { Tytul = "Come Taste The Band", Gatunek = gatunki.Single(g => g.Nazwa == "Rock"), Cena = 8.99M, Autor = autorzy.Single(a => a.Nazwa == "Deep Purple"), Okladka = "/Content/Images/placeholder.gif" },
                new Ksiazka { Tytul = "Deep Purple In Rock", Gatunek = gatunki.Single(g => g.Nazwa == "Rock"), Cena = 8.99M, Autor = autorzy.Single(a => a.Nazwa == "Deep Purple"), Okladka = "/Content/Images/placeholder.gif" },
                new Ksiazka { Tytul = "Fireball", Gatunek = gatunki.Single(g => g.Nazwa == "Rock"), Cena = 8.99M, Autor = autorzy.Single(a => a.Nazwa == "Deep Purple"), Okladka = "/Content/Images/placeholder.gif" },
                new Ksiazka { Tytul = "Machine Head", Gatunek = gatunki.Single(g => g.Nazwa == "Rock"), Cena = 8.99M, Autor = autorzy.Single(a => a.Nazwa == "Deep Purple"), Okladka = "/Content/Images/placeholder.gif" },
                new Ksiazka { Tytul = "MK III The Final Concerts [Disc 1]", Gatunek = gatunki.Single(g => g.Nazwa == "Rock"), Cena = 8.99M, Autor = autorzy.Single(a => a.Nazwa == "Deep Purple"), Okladka = "/Content/Images/placeholder.gif" },
                new Ksiazka { Tytul = "Purpendicular", Gatunek = gatunki.Single(g => g.Nazwa == "Rock"), Cena = 8.99M, Autor = autorzy.Single(a => a.Nazwa == "Deep Purple"), Okladka = "/Content/Images/placeholder.gif" },
                new Ksiazka { Tytul = "Slaves And Masters", Gatunek = gatunki.Single(g => g.Nazwa == "Rock"), Cena = 8.99M, Autor = autorzy.Single(a => a.Nazwa == "Deep Purple"), Okladka = "/Content/Images/placeholder.gif" },
                new Ksiazka { Tytul = "Stormbringer", Gatunek = gatunki.Single(g => g.Nazwa == "Rock"), Cena = 8.99M, Autor = autorzy.Single(a => a.Nazwa == "Deep Purple"), Okladka = "/Content/Images/placeholder.gif" },
                new Ksiazka { Tytul = "The Battle Rages On", Gatunek = gatunki.Single(g => g.Nazwa == "Rock"), Cena = 8.99M, Autor = autorzy.Single(a => a.Nazwa == "Deep Purple"), Okladka = "/Content/Images/placeholder.gif" },
                new Ksiazka { Tytul = "The Final Concerts (Disc 2)", Gatunek = gatunki.Single(g => g.Nazwa == "Rock"), Cena = 8.99M, Autor = autorzy.Single(a => a.Nazwa == "Deep Purple"), Okladka = "/Content/Images/placeholder.gif" },
                new Ksiazka { Tytul = "Outbreak", Gatunek = gatunki.Single(g => g.Nazwa == "Jazz"), Cena = 8.99M, Autor = autorzy.Single(a => a.Nazwa == "Dennis Chambers"), Okladka = "/Content/Images/placeholder.gif" },
                new Ksiazka { Tytul = "Djavan Ao Vivo - Vol. 02", Gatunek = gatunki.Single(g => g.Nazwa == "Latin"), Cena = 8.99M, Autor = autorzy.Single(a => a.Nazwa == "Djavan"), Okladka = "/Content/Images/placeholder.gif" },
                new Ksiazka { Tytul = "Djavan Ao Vivo - Vol. 1", Gatunek = gatunki.Single(g => g.Nazwa == "Latin"), Cena = 8.99M, Autor = autorzy.Single(a => a.Nazwa == "Djavan"), Okladka = "/Content/Images/placeholder.gif" },
                new Ksiazka { Tytul = "MacArthur Park Suite", Gatunek = gatunki.Single(g => g.Nazwa == "Disco"), Cena = 8.99M, Autor = autorzy.Single(a => a.Nazwa == "Donna Summer"), Okladka = "/Content/Images/placeholder.gif" },
                new Ksiazka { Tytul = "Un-Led-Ed", Gatunek = gatunki.Single(g => g.Nazwa == "Rock"), Cena = 8.99M, Autor = autorzy.Single(a => a.Nazwa == "Dread Zeppelin"), Okladka = "/Content/Images/placeholder.gif" },
                new Ksiazka { Tytul = "The Best of Ed Motta", Gatunek = gatunki.Single(g => g.Nazwa == "Latin"), Cena = 8.99M, Autor = autorzy.Single(a => a.Nazwa == "Ed Motta"), Okladka = "/Content/Images/placeholder.gif" },
                new Ksiazka { Tytul = "Adams, John: The Chairman Dances", Gatunek = gatunki.Single(g => g.Nazwa == "Classical"), Cena = 8.99M, Autor = autorzy.Single(a => a.Nazwa == "Edo de Waart & San Francisco Symphony"), Okladka = "/Content/Images/placeholder.gif" },
                new Ksiazka { Tytul = "Elis Regina-Minha História", Gatunek = gatunki.Single(g => g.Nazwa == "Latin"), Cena = 8.99M, Autor = autorzy.Single(a => a.Nazwa == "Elis Regina"), Okladka = "/Content/Images/placeholder.gif" },
                new Ksiazka { Tytul = "Pachelbel: Canon & Gigue", Gatunek = gatunki.Single(g => g.Nazwa == "Classical"), Cena = 8.99M, Autor = autorzy.Single(a => a.Nazwa == "English Concert & Trevor Pinnock"), Okladka = "/Content/Images/placeholder.gif" },
                new Ksiazka { Tytul = "Unplugged", Gatunek = gatunki.Single(g => g.Nazwa == "Latin"), Cena = 8.99M, Autor = autorzy.Single(a => a.Nazwa == "Eric Clapton"), Okladka = "/Content/Images/placeholder.gif" },
                new Ksiazka { Tytul = "The Cream Of Clapton", Gatunek = gatunki.Single(g => g.Nazwa == "Blues"), Cena = 8.99M, Autor = autorzy.Single(a => a.Nazwa == "Eric Clapton"), Okladka = "/Content/Images/placeholder.gif" },
                new Ksiazka { Tytul = "Unplugged", Gatunek = gatunki.Single(g => g.Nazwa == "Blues"), Cena = 8.99M, Autor = autorzy.Single(a => a.Nazwa == "Eric Clapton"), Okladka = "/Content/Images/placeholder.gif" },
                new Ksiazka { Tytul = "Respighi:Pines of Rome", Gatunek = gatunki.Single(g => g.Nazwa == "Classical"), Cena = 8.99M, Autor = autorzy.Single(a => a.Nazwa == "Eugene Ormandy"), Okladka = "/Content/Images/placeholder.gif" },
                new Ksiazka { Tytul = "Strauss: Waltzes", Gatunek = gatunki.Single(g => g.Nazwa == "Classical"), Cena = 8.99M, Autor = autorzy.Single(a => a.Nazwa == "Eugene Ormandy"), Okladka = "/Content/Images/placeholder.gif" },
                new Ksiazka { Tytul = "King For A Day Fool For A Lifetime", Gatunek = gatunki.Single(g => g.Nazwa == "Rock"), Cena = 8.99M, Autor = autorzy.Single(a => a.Nazwa == "Faith No More"), Okladka = "/Content/Images/placeholder.gif" },
                new Ksiazka { Tytul = "Deixa Entrar", Gatunek = gatunki.Single(g => g.Nazwa == "Latin"), Cena = 8.99M, Autor = autorzy.Single(a => a.Nazwa == "Falamansa"), Okladka = "/Content/Images/placeholder.gif" },
                new Ksiazka { Tytul = "In Your Honor [Disc 1]", Gatunek = gatunki.Single(g => g.Nazwa == "Rock"), Cena = 8.99M, Autor = autorzy.Single(a => a.Nazwa == "Foo Fighters"), Okladka = "/Content/Images/placeholder.gif" },
                new Ksiazka { Tytul = "In Your Honor [Disc 2]", Gatunek = gatunki.Single(g => g.Nazwa == "Rock"), Cena = 8.99M, Autor = autorzy.Single(a => a.Nazwa == "Foo Fighters"), Okladka = "/Content/Images/placeholder.gif" },
                new Ksiazka { Tytul = "The Colour And The Shape", Gatunek = gatunki.Single(g => g.Nazwa == "Rock"), Cena = 8.99M, Autor = autorzy.Single(a => a.Nazwa == "Foo Fighters"), Okladka = "/Content/Images/placeholder.gif" },
                new Ksiazka { Tytul = "Bongo Fury", Gatunek = gatunki.Single(g => g.Nazwa == "Rock"), Cena = 8.99M, Autor = autorzy.Single(a => a.Nazwa == "Frank Zappa & Captain Beefheart"), Okladka = "/Content/Images/placeholder.gif" },
                new Ksiazka { Tytul = "Roda De Funk", Gatunek = gatunki.Single(g => g.Nazwa == "Latin"), Cena = 8.99M, Autor = autorzy.Single(a => a.Nazwa == "Funk Como Le Gusta"), Okladka = "/Content/Images/placeholder.gif" },
                new Ksiazka { Tytul = "Quanta Gente Veio Ver (Live)", Gatunek = gatunki.Single(g => g.Nazwa == "Latin"), Cena = 8.99M, Autor = autorzy.Single(a => a.Nazwa == "Gilberto Gil"), Okladka = "/Content/Images/placeholder.gif" },
                new Ksiazka { Tytul = "Quanta Gente Veio ver--Bônus De Carnaval", Gatunek = gatunki.Single(g => g.Nazwa == "Jazz"), Cena = 8.99M, Autor = autorzy.Single(a => a.Nazwa == "Gilberto Gil"), Okladka = "/Content/Images/placeholder.gif" },
                new Ksiazka { Tytul = "Faceless", Gatunek = gatunki.Single(g => g.Nazwa == "Metal"), Cena = 8.99M, Autor = autorzy.Single(a => a.Nazwa == "Godsmack"), Okladka = "/Content/Images/placeholder.gif" },
                new Ksiazka { Tytul = "Meus Momentos", Gatunek = gatunki.Single(g => g.Nazwa == "Latin"), Cena = 8.99M, Autor = autorzy.Single(a => a.Nazwa == "Gonzaguinha"), Okladka = "/Content/Images/placeholder.gif" },
                new Ksiazka { Tytul = "Nielsen: The Six Symphonies", Gatunek = gatunki.Single(g => g.Nazwa == "Classical"), Cena = 8.99M, Autor = autorzy.Single(a => a.Nazwa == "Göteborgs Symfoniker & Neeme Järvi"), Okladka = "/Content/Images/placeholder.gif" },
                new Ksiazka { Tytul = "Appetite for Destruction", Gatunek = gatunki.Single(g => g.Nazwa == "Rock"), Cena = 8.99M, Autor = autorzy.Single(a => a.Nazwa == "Guns N' Roses"), Okladka = "/Content/Images/placeholder.gif" },
                new Ksiazka { Tytul = "Use Your Illusion I", Gatunek = gatunki.Single(g => g.Nazwa == "Rock"), Cena = 8.99M, Autor = autorzy.Single(a => a.Nazwa == "Guns N' Roses"), Okladka = "/Content/Images/placeholder.gif" },
                new Ksiazka { Tytul = "Use Your Illusion II", Gatunek = gatunki.Single(g => g.Nazwa == "Metal"), Cena = 8.99M, Autor = autorzy.Single(a => a.Nazwa == "Guns N' Roses"), Okladka = "/Content/Images/placeholder.gif" },
                new Ksiazka { Tytul = "Blue Moods", Gatunek = gatunki.Single(g => g.Nazwa == "Jazz"), Cena = 8.99M, Autor = autorzy.Single(a => a.Nazwa == "Incognito"), Okladka = "/Content/Images/placeholder.gif" },
                new Ksiazka { Tytul = "A Matter of Life and Death", Gatunek = gatunki.Single(g => g.Nazwa == "Rock"), Cena = 8.99M, Autor = autorzy.Single(a => a.Nazwa == "Iron Maiden"), Okladka = "/Content/Images/placeholder.gif" },
                new Ksiazka { Tytul = "Brave New World", Gatunek = gatunki.Single(g => g.Nazwa == "Rock"), Cena = 8.99M, Autor = autorzy.Single(a => a.Nazwa == "Iron Maiden"), Okladka = "/Content/Images/placeholder.gif" },
                new Ksiazka { Tytul = "Fear Of The Dark", Gatunek = gatunki.Single(g => g.Nazwa == "Rock"), Cena = 8.99M, Autor = autorzy.Single(a => a.Nazwa == "Iron Maiden"), Okladka = "/Content/Images/placeholder.gif" },
                new Ksiazka { Tytul = "Live At Donington 1992 (Disc 1)", Gatunek = gatunki.Single(g => g.Nazwa == "Rock"), Cena = 8.99M, Autor = autorzy.Single(a => a.Nazwa == "Iron Maiden"), Okladka = "/Content/Images/placeholder.gif" },
                new Ksiazka { Tytul = "Live At Donington 1992 (Disc 2)", Gatunek = gatunki.Single(g => g.Nazwa == "Rock"), Cena = 8.99M, Autor = autorzy.Single(a => a.Nazwa == "Iron Maiden"), Okladka = "/Content/Images/placeholder.gif" },
                new Ksiazka { Tytul = "Rock In Rio [CD2]", Gatunek = gatunki.Single(g => g.Nazwa == "Rock"), Cena = 8.99M, Autor = autorzy.Single(a => a.Nazwa == "Iron Maiden"), Okladka = "/Content/Images/placeholder.gif" },
                new Ksiazka { Tytul = "The Number of The Beast", Gatunek = gatunki.Single(g => g.Nazwa == "Rock"), Cena = 8.99M, Autor = autorzy.Single(a => a.Nazwa == "Iron Maiden"), Okladka = "/Content/Images/placeholder.gif" },
                new Ksiazka { Tytul = "The X Factor", Gatunek = gatunki.Single(g => g.Nazwa == "Rock"), Cena = 8.99M, Autor = autorzy.Single(a => a.Nazwa == "Iron Maiden"), Okladka = "/Content/Images/placeholder.gif" },
                new Ksiazka { Tytul = "Virtual XI", Gatunek = gatunki.Single(g => g.Nazwa == "Rock"), Cena = 8.99M, Autor = autorzy.Single(a => a.Nazwa == "Iron Maiden"), Okladka = "/Content/Images/placeholder.gif" },
                new Ksiazka { Tytul = "A Real Dead One", Gatunek = gatunki.Single(g => g.Nazwa == "Metal"), Cena = 8.99M, Autor = autorzy.Single(a => a.Nazwa == "Iron Maiden"), Okladka = "/Content/Images/placeholder.gif" },
                new Ksiazka { Tytul = "A Real Live One", Gatunek = gatunki.Single(g => g.Nazwa == "Metal"), Cena = 8.99M, Autor = autorzy.Single(a => a.Nazwa == "Iron Maiden"), Okladka = "/Content/Images/placeholder.gif" },
                new Ksiazka { Tytul = "Live After Death", Gatunek = gatunki.Single(g => g.Nazwa == "Metal"), Cena = 8.99M, Autor = autorzy.Single(a => a.Nazwa == "Iron Maiden"), Okladka = "/Content/Images/placeholder.gif" },
                new Ksiazka { Tytul = "No Prayer For The Dying", Gatunek = gatunki.Single(g => g.Nazwa == "Metal"), Cena = 8.99M, Autor = autorzy.Single(a => a.Nazwa == "Iron Maiden"), Okladka = "/Content/Images/placeholder.gif" },
                new Ksiazka { Tytul = "Piece Of Mind", Gatunek = gatunki.Single(g => g.Nazwa == "Metal"), Cena = 8.99M, Autor = autorzy.Single(a => a.Nazwa == "Iron Maiden"), Okladka = "/Content/Images/placeholder.gif" },
                new Ksiazka { Tytul = "Powerslave", Gatunek = gatunki.Single(g => g.Nazwa == "Metal"), Cena = 8.99M, Autor = autorzy.Single(a => a.Nazwa == "Iron Maiden"), Okladka = "/Content/Images/placeholder.gif" },
                new Ksiazka { Tytul = "Rock In Rio [CD1]", Gatunek = gatunki.Single(g => g.Nazwa == "Metal"), Cena = 8.99M, Autor = autorzy.Single(a => a.Nazwa == "Iron Maiden"), Okladka = "/Content/Images/placeholder.gif" },
                new Ksiazka { Tytul = "Rock In Rio [CD2]", Gatunek = gatunki.Single(g => g.Nazwa == "Metal"), Cena = 8.99M, Autor = autorzy.Single(a => a.Nazwa == "Iron Maiden"), Okladka = "/Content/Images/placeholder.gif" },
                new Ksiazka { Tytul = "Seventh Son of a Seventh Son", Gatunek = gatunki.Single(g => g.Nazwa == "Metal"), Cena = 8.99M, Autor = autorzy.Single(a => a.Nazwa == "Iron Maiden"), Okladka = "/Content/Images/placeholder.gif" },
                new Ksiazka { Tytul = "Somewhere in Time", Gatunek = gatunki.Single(g => g.Nazwa == "Metal"), Cena = 8.99M, Autor = autorzy.Single(a => a.Nazwa == "Iron Maiden"), Okladka = "/Content/Images/placeholder.gif" },
                new Ksiazka { Tytul = "The Number of The Beast", Gatunek = gatunki.Single(g => g.Nazwa == "Metal"), Cena = 8.99M, Autor = autorzy.Single(a => a.Nazwa == "Iron Maiden"), Okladka = "/Content/Images/placeholder.gif" },
                new Ksiazka { Tytul = "Iron Maiden", Gatunek = gatunki.Single(g => g.Nazwa == "Blues"), Cena = 8.99M, Autor = autorzy.Single(a => a.Nazwa == "Iron Maiden"), Okladka = "/Content/Images/placeholder.gif" },
                new Ksiazka { Tytul = "Mascagni: Cavalleria Rusticana", Gatunek = gatunki.Single(g => g.Nazwa == "Classical"), Cena = 8.99M, Autor = autorzy.Single(a => a.Nazwa == "James Levine"), Okladka = "/Content/Images/placeholder.gif" },
                new Ksiazka { Tytul = "Emergency On Planet Earth", Gatunek = gatunki.Single(g => g.Nazwa == "Rock"), Cena = 8.99M, Autor = autorzy.Single(a => a.Nazwa == "Jamiroquai"), Okladka = "/Content/Images/placeholder.gif" },
                new Ksiazka { Tytul = "Are You Experienced?", Gatunek = gatunki.Single(g => g.Nazwa == "Rock"), Cena = 8.99M, Autor = autorzy.Single(a => a.Nazwa == "Jimi Hendrix"), Okladka = "/Content/Images/placeholder.gif" },
                new Ksiazka { Tytul = "Surfing with the Alien (Remastered)", Gatunek = gatunki.Single(g => g.Nazwa == "Rock"), Cena = 8.99M, Autor = autorzy.Single(a => a.Nazwa == "Joe Satriani"), Okladka = "/Content/Images/placeholder.gif" },
                new Ksiazka { Tytul = "Jorge Ben Jor 25 Anos", Gatunek = gatunki.Single(g => g.Nazwa == "Latin"), Cena = 8.99M, Autor = autorzy.Single(a => a.Nazwa == "Jorge Ben"), Okladka = "/Content/Images/placeholder.gif" },
                new Ksiazka { Tytul = "Jota Quest-1995", Gatunek = gatunki.Single(g => g.Nazwa == "Latin"), Cena = 8.99M, Autor = autorzy.Single(a => a.Nazwa == "Jota Quest"), Okladka = "/Content/Images/placeholder.gif" },
                new Ksiazka { Tytul = "Living After Midnight", Gatunek = gatunki.Single(g => g.Nazwa == "Metal"), Cena = 8.99M, Autor = autorzy.Single(a => a.Nazwa == "Judas Priest"), Okladka = "/Content/Images/placeholder.gif" },
                new Ksiazka { Tytul = "Weill: The Seven Deadly Sins", Gatunek = gatunki.Single(g => g.Nazwa == "Classical"), Cena = 8.99M, Autor = autorzy.Single(a => a.Nazwa == "Kent Nagano and Orchestre de l'Opéra de Lyon"), Okladka = "/Content/Images/placeholder.gif" },
                new Ksiazka { Tytul = "Greatest Kiss", Gatunek = gatunki.Single(g => g.Nazwa == "Rock"), Cena = 8.99M, Autor = autorzy.Single(a => a.Nazwa == "Kiss"), Okladka = "/Content/Images/placeholder.gif" },
                new Ksiazka { Tytul = "Unplugged [Live]", Gatunek = gatunki.Single(g => g.Nazwa == "Rock"), Cena = 8.99M, Autor = autorzy.Single(a => a.Nazwa == "Kiss"), Okladka = "/Content/Images/placeholder.gif" },
                new Ksiazka { Tytul = "BBC Sessions [Disc 1] [Live]", Gatunek = gatunki.Single(g => g.Nazwa == "Rock"), Cena = 8.99M, Autor = autorzy.Single(a => a.Nazwa == "Led Zeppelin"), Okladka = "/Content/Images/placeholder.gif" },
                new Ksiazka { Tytul = "BBC Sessions [Disc 2] [Live]", Gatunek = gatunki.Single(g => g.Nazwa == "Rock"), Cena = 8.99M, Autor = autorzy.Single(a => a.Nazwa == "Led Zeppelin"), Okladka = "/Content/Images/placeholder.gif" },
                new Ksiazka { Tytul = "Coda", Gatunek = gatunki.Single(g => g.Nazwa == "Rock"), Cena = 8.99M, Autor = autorzy.Single(a => a.Nazwa == "Led Zeppelin"), Okladka = "/Content/Images/placeholder.gif" },
                new Ksiazka { Tytul = "Houses Of The Holy", Gatunek = gatunki.Single(g => g.Nazwa == "Rock"), Cena = 8.99M, Autor = autorzy.Single(a => a.Nazwa == "Led Zeppelin"), Okladka = "/Content/Images/placeholder.gif" },
                new Ksiazka { Tytul = "In Through The Out Door", Gatunek = gatunki.Single(g => g.Nazwa == "Rock"), Cena = 8.99M, Autor = autorzy.Single(a => a.Nazwa == "Led Zeppelin"), Okladka = "/Content/Images/placeholder.gif" },
                new Ksiazka { Tytul = "IV", Gatunek = gatunki.Single(g => g.Nazwa == "Rock"), Cena = 8.99M, Autor = autorzy.Single(a => a.Nazwa == "Led Zeppelin"), Okladka = "/Content/Images/placeholder.gif" },
                new Ksiazka { Tytul = "Led Zeppelin I", Gatunek = gatunki.Single(g => g.Nazwa == "Rock"), Cena = 8.99M, Autor = autorzy.Single(a => a.Nazwa == "Led Zeppelin"), Okladka = "/Content/Images/placeholder.gif" },
                new Ksiazka { Tytul = "Led Zeppelin II", Gatunek = gatunki.Single(g => g.Nazwa == "Rock"), Cena = 8.99M, Autor = autorzy.Single(a => a.Nazwa == "Led Zeppelin"), Okladka = "/Content/Images/placeholder.gif" },
                new Ksiazka { Tytul = "Led Zeppelin III", Gatunek = gatunki.Single(g => g.Nazwa == "Rock"), Cena = 8.99M, Autor = autorzy.Single(a => a.Nazwa == "Led Zeppelin"), Okladka = "/Content/Images/placeholder.gif" },
                new Ksiazka { Tytul = "Physical Graffiti [Disc 1]", Gatunek = gatunki.Single(g => g.Nazwa == "Rock"), Cena = 8.99M, Autor = autorzy.Single(a => a.Nazwa == "Led Zeppelin"), Okladka = "/Content/Images/placeholder.gif" },
                new Ksiazka { Tytul = "Physical Graffiti [Disc 2]", Gatunek = gatunki.Single(g => g.Nazwa == "Rock"), Cena = 8.99M, Autor = autorzy.Single(a => a.Nazwa == "Led Zeppelin"), Okladka = "/Content/Images/placeholder.gif" },
                new Ksiazka { Tytul = "Presence", Gatunek = gatunki.Single(g => g.Nazwa == "Rock"), Cena = 8.99M, Autor = autorzy.Single(a => a.Nazwa == "Led Zeppelin"), Okladka = "/Content/Images/placeholder.gif" },
                new Ksiazka { Tytul = "The Song Remains The Same (Disc 1)", Gatunek = gatunki.Single(g => g.Nazwa == "Rock"), Cena = 8.99M, Autor = autorzy.Single(a => a.Nazwa == "Led Zeppelin"), Okladka = "/Content/Images/placeholder.gif" },
                new Ksiazka { Tytul = "The Song Remains The Same (Disc 2)", Gatunek = gatunki.Single(g => g.Nazwa == "Rock"), Cena = 8.99M, Autor = autorzy.Single(a => a.Nazwa == "Led Zeppelin"), Okladka = "/Content/Images/placeholder.gif" },
                new Ksiazka { Tytul = "Mais Do Mesmo", Gatunek = gatunki.Single(g => g.Nazwa == "Latin"), Cena = 8.99M, Autor = autorzy.Single(a => a.Nazwa == "Legião Urbana"), Okladka = "/Content/Images/placeholder.gif" },
                new Ksiazka { Tytul = "Greatest Hits", Gatunek = gatunki.Single(g => g.Nazwa == "Reggae"), Cena = 8.99M, Autor = autorzy.Single(a => a.Nazwa == "Lenny Kravitz"), Okladka = "/Content/Images/placeholder.gif" },
                new Ksiazka { Tytul = "Greatest Hits", Gatunek = gatunki.Single(g => g.Nazwa == "Rock"), Cena = 8.99M, Autor = autorzy.Single(a => a.Nazwa == "Lenny Kravitz"), Okladka = "/Content/Images/placeholder.gif" },
                new Ksiazka { Tytul = "Greatest Hits", Gatunek = gatunki.Single(g => g.Nazwa == "Metal"), Cena = 8.99M, Autor = autorzy.Single(a => a.Nazwa == "Lenny Kravitz"), Okladka = "/Content/Images/placeholder.gif" },
                new Ksiazka { Tytul = "Tchaikovsky: The Nutcracker", Gatunek = gatunki.Single(g => g.Nazwa == "Classical"), Cena = 8.99M, Autor = autorzy.Single(a => a.Nazwa == "London Symphony Orchestra & Sir Charles Mackerras"), Okladka = "/Content/Images/placeholder.gif" },
                new Ksiazka { Tytul = "Duos II", Gatunek = gatunki.Single(g => g.Nazwa == "Latin"), Cena = 8.99M, Autor = autorzy.Single(a => a.Nazwa == "Luciana Souza/Romero Lubambo"), Okladka = "/Content/Images/placeholder.gif" },
                new Ksiazka { Tytul = "Chill: Brazil (Disc 1)", Gatunek = gatunki.Single(g => g.Nazwa == "Latin"), Cena = 8.99M, Autor = autorzy.Single(a => a.Nazwa == "Marcos Valle"), Okladka = "/Content/Images/placeholder.gif" },
                new Ksiazka { Tytul = "Misplaced Childhood", Gatunek = gatunki.Single(g => g.Nazwa == "Rock"), Cena = 8.99M, Autor = autorzy.Single(a => a.Nazwa == "Marillion"), Okladka = "/Content/Images/placeholder.gif" },
                new Ksiazka { Tytul = "Barulhinho Bom", Gatunek = gatunki.Single(g => g.Nazwa == "Latin"), Cena = 8.99M, Autor = autorzy.Single(a => a.Nazwa == "Marisa Monte"), Okladka = "/Content/Images/placeholder.gif" },
                new Ksiazka { Tytul = "Szymanowski: Piano Works, Vol. 1", Gatunek = gatunki.Single(g => g.Nazwa == "Classical"), Cena = 8.99M, Autor = autorzy.Single(a => a.Nazwa == "Martin Roscoe"), Okladka = "/Content/Images/placeholder.gif" },
                new Ksiazka { Tytul = "...And Justice For All", Gatunek = gatunki.Single(g => g.Nazwa == "Metal"), Cena = 8.99M, Autor = autorzy.Single(a => a.Nazwa == "Metallica"), Okladka = "/Content/Images/placeholder.gif" },
                new Ksiazka { Tytul = "Black Album", Gatunek = gatunki.Single(g => g.Nazwa == "Metal"), Cena = 8.99M, Autor = autorzy.Single(a => a.Nazwa == "Metallica"), Okladka = "/Content/Images/placeholder.gif" },
                new Ksiazka { Tytul = "Garage Inc. (Disc 1)", Gatunek = gatunki.Single(g => g.Nazwa == "Metal"), Cena = 8.99M, Autor = autorzy.Single(a => a.Nazwa == "Metallica"), Okladka = "/Content/Images/placeholder.gif" },
                new Ksiazka { Tytul = "Garage Inc. (Disc 2)", Gatunek = gatunki.Single(g => g.Nazwa == "Metal"), Cena = 8.99M, Autor = autorzy.Single(a => a.Nazwa == "Metallica"), Okladka = "/Content/Images/placeholder.gif" },
                new Ksiazka { Tytul = "Load", Gatunek = gatunki.Single(g => g.Nazwa == "Metal"), Cena = 8.99M, Autor = autorzy.Single(a => a.Nazwa == "Metallica"), Okladka = "/Content/Images/placeholder.gif" },
                new Ksiazka { Tytul = "Master Of Puppets", Gatunek = gatunki.Single(g => g.Nazwa == "Metal"), Cena = 8.99M, Autor = autorzy.Single(a => a.Nazwa == "Metallica"), Okladka = "/Content/Images/placeholder.gif" },
                new Ksiazka { Tytul = "ReLoad", Gatunek = gatunki.Single(g => g.Nazwa == "Metal"), Cena = 8.99M, Autor = autorzy.Single(a => a.Nazwa == "Metallica"), Okladka = "/Content/Images/placeholder.gif" },
                new Ksiazka { Tytul = "Ride The Lightning", Gatunek = gatunki.Single(g => g.Nazwa == "Metal"), Cena = 8.99M, Autor = autorzy.Single(a => a.Nazwa == "Metallica"), Okladka = "/Content/Images/placeholder.gif" },
                new Ksiazka { Tytul = "St. Anger", Gatunek = gatunki.Single(g => g.Nazwa == "Metal"), Cena = 8.99M, Autor = autorzy.Single(a => a.Nazwa == "Metallica"), Okladka = "/Content/Images/placeholder.gif" },
                new Ksiazka { Tytul = "Berlioz: Symphonie Fantastique", Gatunek = gatunki.Single(g => g.Nazwa == "Classical"), Cena = 8.99M, Autor = autorzy.Single(a => a.Nazwa == "Michael Tilson Thomas & San Francisco Symphony"), Okladka = "/Content/Images/placeholder.gif" },
                new Ksiazka { Tytul = "Prokofiev: Romeo & Juliet", Gatunek = gatunki.Single(g => g.Nazwa == "Classical"), Cena = 8.99M, Autor = autorzy.Single(a => a.Nazwa == "Michael Tilson Thomas & San Francisco Symphony"), Okladka = "/Content/Images/placeholder.gif" },
                new Ksiazka { Tytul = "Miles Ahead", Gatunek = gatunki.Single(g => g.Nazwa == "Jazz"), Cena = 8.99M, Autor = autorzy.Single(a => a.Nazwa == "Miles Davis"), Okladka = "/Content/Images/placeholder.gif" },
                new Ksiazka { Tytul = "The Essential Miles Davis [Disc 1]", Gatunek = gatunki.Single(g => g.Nazwa == "Jazz"), Cena = 8.99M, Autor = autorzy.Single(a => a.Nazwa == "Miles Davis"), Okladka = "/Content/Images/placeholder.gif" },
                new Ksiazka { Tytul = "The Essential Miles Davis [Disc 2]", Gatunek = gatunki.Single(g => g.Nazwa == "Jazz"), Cena = 8.99M, Autor = autorzy.Single(a => a.Nazwa == "Miles Davis"), Okladka = "/Content/Images/placeholder.gif" },
                new Ksiazka { Tytul = "Milton Nascimento Ao Vivo", Gatunek = gatunki.Single(g => g.Nazwa == "Latin"), Cena = 8.99M, Autor = autorzy.Single(a => a.Nazwa == "Milton Nascimento"), Okladka = "/Content/Images/placeholder.gif" },
                new Ksiazka { Tytul = "Minas", Gatunek = gatunki.Single(g => g.Nazwa == "Latin"), Cena = 8.99M, Autor = autorzy.Single(a => a.Nazwa == "Milton Nascimento"), Okladka = "/Content/Images/placeholder.gif" },
                new Ksiazka { Tytul = "Motley Crue Greatest Hits", Gatunek = gatunki.Single(g => g.Nazwa == "Metal"), Cena = 8.99M, Autor = autorzy.Single(a => a.Nazwa == "Mötley Crüe"), Okladka = "/Content/Images/placeholder.gif" },
                new Ksiazka { Tytul = "Ace Of Spades", Gatunek = gatunki.Single(g => g.Nazwa == "Metal"), Cena = 8.99M, Autor = autorzy.Single(a => a.Nazwa == "Motörhead"), Okladka = "/Content/Images/placeholder.gif" },
                new Ksiazka { Tytul = "Mozart: Chamber Music", Gatunek = gatunki.Single(g => g.Nazwa == "Classical"), Cena = 8.99M, Autor = autorzy.Single(a => a.Nazwa == "Nash Ensemble"), Okladka = "/Content/Images/placeholder.gif" },
                new Ksiazka { Tytul = "The Best of Beethoven", Gatunek = gatunki.Single(g => g.Nazwa == "Classical"), Cena = 8.99M, Autor = autorzy.Single(a => a.Nazwa == "Nicolaus Esterhazy Sinfonia"), Okladka = "/Content/Images/placeholder.gif" },
                new Ksiazka { Tytul = "Nevermind", Gatunek = gatunki.Single(g => g.Nazwa == "Rock"), Cena = 8.99M, Autor = autorzy.Single(a => a.Nazwa == "Nirvana"), Okladka = "/Content/Images/placeholder.gif" },
                new Ksiazka { Tytul = "Compositores", Gatunek = gatunki.Single(g => g.Nazwa == "Rock"), Cena = 8.99M, Autor = autorzy.Single(a => a.Nazwa == "O Terço"), Okladka = "/Content/Images/placeholder.gif" },
                new Ksiazka { Tytul = "Olodum", Gatunek = gatunki.Single(g => g.Nazwa == "Latin"), Cena = 8.99M, Autor = autorzy.Single(a => a.Nazwa == "Olodum"), Okladka = "/Content/Images/placeholder.gif" },
                new Ksiazka { Tytul = "Bach: The Brandenburg Concertos", Gatunek = gatunki.Single(g => g.Nazwa == "Classical"), Cena = 8.99M, Autor = autorzy.Single(a => a.Nazwa == "Orchestra of The Age of Enlightenment"), Okladka = "/Content/Images/placeholder.gif" },
                new Ksiazka { Tytul = "Acústico MTV", Gatunek = gatunki.Single(g => g.Nazwa == "Latin"), Cena = 8.99M, Autor = autorzy.Single(a => a.Nazwa == "Os Paralamas Do Sucesso"), Okladka = "/Content/Images/placeholder.gif" },
                new Ksiazka { Tytul = "Arquivo II", Gatunek = gatunki.Single(g => g.Nazwa == "Latin"), Cena = 8.99M, Autor = autorzy.Single(a => a.Nazwa == "Os Paralamas Do Sucesso"), Okladka = "/Content/Images/placeholder.gif" },
                new Ksiazka { Tytul = "Arquivo Os Paralamas Do Sucesso", Gatunek = gatunki.Single(g => g.Nazwa == "Latin"), Cena = 8.99M, Autor = autorzy.Single(a => a.Nazwa == "Os Paralamas Do Sucesso"), Okladka = "/Content/Images/placeholder.gif" },
                new Ksiazka { Tytul = "Tribute", Gatunek = gatunki.Single(g => g.Nazwa == "Metal"), Cena = 8.99M, Autor = autorzy.Single(a => a.Nazwa == "Ozzy Osbourne"), Okladka = "/Content/Images/placeholder.gif" },
                new Ksiazka { Tytul = "Bark at the Moon (Remastered)", Gatunek = gatunki.Single(g => g.Nazwa == "Rock"), Cena = 8.99M, Autor = autorzy.Single(a => a.Nazwa == "Ozzy Osbourne"), Okladka = "/Content/Images/placeholder.gif" },
                new Ksiazka { Tytul = "Blizzard of Ozz", Gatunek = gatunki.Single(g => g.Nazwa == "Rock"), Cena = 8.99M, Autor = autorzy.Single(a => a.Nazwa == "Ozzy Osbourne"), Okladka = "/Content/Images/placeholder.gif" },
                new Ksiazka { Tytul = "Diary of a Madman (Remastered)", Gatunek = gatunki.Single(g => g.Nazwa == "Rock"), Cena = 8.99M, Autor = autorzy.Single(a => a.Nazwa == "Ozzy Osbourne"), Okladka = "/Content/Images/placeholder.gif" },
                new Ksiazka { Tytul = "No More Tears (Remastered)", Gatunek = gatunki.Single(g => g.Nazwa == "Rock"), Cena = 8.99M, Autor = autorzy.Single(a => a.Nazwa == "Ozzy Osbourne"), Okladka = "/Content/Images/placeholder.gif" },
                new Ksiazka { Tytul = "Speak of the Devil", Gatunek = gatunki.Single(g => g.Nazwa == "Rock"), Cena = 8.99M, Autor = autorzy.Single(a => a.Nazwa == "Ozzy Osbourne"), Okladka = "/Content/Images/placeholder.gif" },
                new Ksiazka { Tytul = "Walking Into Clarksdale", Gatunek = gatunki.Single(g => g.Nazwa == "Rock"), Cena = 8.99M, Autor = autorzy.Single(a => a.Nazwa == "Page & Plant"), Okladka = "/Content/Images/placeholder.gif" },
                new Ksiazka { Tytul = "The Beast Live", Gatunek = gatunki.Single(g => g.Nazwa == "Rock"), Cena = 8.99M, Autor = autorzy.Single(a => a.Nazwa == "Paul D'Ianno"), Okladka = "/Content/Images/placeholder.gif" },
                new Ksiazka { Tytul = "Live On Two Legs [Live]", Gatunek = gatunki.Single(g => g.Nazwa == "Rock"), Cena = 8.99M, Autor = autorzy.Single(a => a.Nazwa == "Pearl Jam"), Okladka = "/Content/Images/placeholder.gif" },
                new Ksiazka { Tytul = "Riot Act", Gatunek = gatunki.Single(g => g.Nazwa == "Rock"), Cena = 8.99M, Autor = autorzy.Single(a => a.Nazwa == "Pearl Jam"), Okladka = "/Content/Images/placeholder.gif" },
                new Ksiazka { Tytul = "Ten", Gatunek = gatunki.Single(g => g.Nazwa == "Rock"), Cena = 8.99M, Autor = autorzy.Single(a => a.Nazwa == "Pearl Jam"), Okladka = "/Content/Images/placeholder.gif" },
                new Ksiazka { Tytul = "Vs.", Gatunek = gatunki.Single(g => g.Nazwa == "Rock"), Cena = 8.99M, Autor = autorzy.Single(a => a.Nazwa == "Pearl Jam"), Okladka = "/Content/Images/placeholder.gif" },
                new Ksiazka { Tytul = "Dark Side Of The Moon", Gatunek = gatunki.Single(g => g.Nazwa == "Rock"), Cena = 8.99M, Autor = autorzy.Single(a => a.Nazwa == "Pink Floyd"), Okladka = "/Content/Images/placeholder.gif" },
                new Ksiazka { Tytul = "Greatest Hits I", Gatunek = gatunki.Single(g => g.Nazwa == "Rock"), Cena = 8.99M, Autor = autorzy.Single(a => a.Nazwa == "Queen"), Okladka = "/Content/Images/placeholder.gif" },
                new Ksiazka { Tytul = "Greatest Hits II", Gatunek = gatunki.Single(g => g.Nazwa == "Rock"), Cena = 8.99M, Autor = autorzy.Single(a => a.Nazwa == "Queen"), Okladka = "/Content/Images/placeholder.gif" },
                new Ksiazka { Tytul = "News Of The World", Gatunek = gatunki.Single(g => g.Nazwa == "Rock"), Cena = 8.99M, Autor = autorzy.Single(a => a.Nazwa == "Queen"), Okladka = "/Content/Images/placeholder.gif" },
                new Ksiazka { Tytul = "New Adventures In Hi-Fi", Gatunek = gatunki.Single(g => g.Nazwa == "Rock"), Cena = 8.99M, Autor = autorzy.Single(a => a.Nazwa == "R.E.M."), Okladka = "/Content/Images/placeholder.gif" },
                new Ksiazka { Tytul = "Raul Seixas", Gatunek = gatunki.Single(g => g.Nazwa == "Rock"), Cena = 8.99M, Autor = autorzy.Single(a => a.Nazwa == "Raul Seixas"), Okladka = "/Content/Images/placeholder.gif" },
                new Ksiazka { Tytul = "By The Way", Gatunek = gatunki.Single(g => g.Nazwa == "Rock"), Cena = 8.99M, Autor = autorzy.Single(a => a.Nazwa == "Red Hot Chili Peppers"), Okladka = "/Content/Images/placeholder.gif" },
                new Ksiazka { Tytul = "Californication", Gatunek = gatunki.Single(g => g.Nazwa == "Rock"), Cena = 8.99M, Autor = autorzy.Single(a => a.Nazwa == "Red Hot Chili Peppers"), Okladka = "/Content/Images/placeholder.gif" },
                new Ksiazka { Tytul = "Purcell: The Fairy Queen", Gatunek = gatunki.Single(g => g.Nazwa == "Classical"), Cena = 8.99M, Autor = autorzy.Single(a => a.Nazwa == "Roger Norrington, London Classical Players"), Okladka = "/Content/Images/placeholder.gif" },
                new Ksiazka { Tytul = "Haydn: Symphonies 99 - 104", Gatunek = gatunki.Single(g => g.Nazwa == "Classical"), Cena = 8.99M, Autor = autorzy.Single(a => a.Nazwa == "Royal Philharmonic Orchestra & Sir Thomas Beecham"), Okladka = "/Content/Images/placeholder.gif" },
                new Ksiazka { Tytul = "Retrospective I (1974-1980)", Gatunek = gatunki.Single(g => g.Nazwa == "Rock"), Cena = 8.99M, Autor = autorzy.Single(a => a.Nazwa == "Rush"), Okladka = "/Content/Images/placeholder.gif" },
                new Ksiazka { Tytul = "Santana - As Years Go By", Gatunek = gatunki.Single(g => g.Nazwa == "Rock"), Cena = 8.99M, Autor = autorzy.Single(a => a.Nazwa == "Santana"), Okladka = "/Content/Images/placeholder.gif" },
                new Ksiazka { Tytul = "Santana Live", Gatunek = gatunki.Single(g => g.Nazwa == "Rock"), Cena = 8.99M, Autor = autorzy.Single(a => a.Nazwa == "Santana"), Okladka = "/Content/Images/placeholder.gif" },
                new Ksiazka { Tytul = "Supernatural", Gatunek = gatunki.Single(g => g.Nazwa == "Rock"), Cena = 8.99M, Autor = autorzy.Single(a => a.Nazwa == "Santana"), Okladka = "/Content/Images/placeholder.gif" },
                new Ksiazka { Tytul = "Handel: The Messiah (Highlights)", Gatunek = gatunki.Single(g => g.Nazwa == "Classical"), Cena = 8.99M, Autor = autorzy.Single(a => a.Nazwa == "Scholars Baroque Ensemble"), Okladka = "/Content/Images/placeholder.gif" },
                new Ksiazka { Tytul = "Prokofiev: Symphony No.1", Gatunek = gatunki.Single(g => g.Nazwa == "Classical"), Cena = 8.99M, Autor = autorzy.Single(a => a.Nazwa == "Sergei Prokofiev & Yuri Temirkanov"), Okladka = "/Content/Images/placeholder.gif" },
                new Ksiazka { Tytul = "Wagner: Favourite Overtures", Gatunek = gatunki.Single(g => g.Nazwa == "Classical"), Cena = 8.99M, Autor = autorzy.Single(a => a.Nazwa == "Sir Georg Solti & Wiener Philharmoniker"), Okladka = "/Content/Images/placeholder.gif" },
                new Ksiazka { Tytul = "Maquinarama", Gatunek = gatunki.Single(g => g.Nazwa == "Rock"), Cena = 8.99M, Autor = autorzy.Single(a => a.Nazwa == "Skank"), Okladka = "/Content/Images/placeholder.gif" },
                new Ksiazka { Tytul = "O Samba Poconé", Gatunek = gatunki.Single(g => g.Nazwa == "Rock"), Cena = 8.99M, Autor = autorzy.Single(a => a.Nazwa == "Skank"), Okladka = "/Content/Images/placeholder.gif" },
                new Ksiazka { Tytul = "A-Sides", Gatunek = gatunki.Single(g => g.Nazwa == "Rock"), Cena = 8.99M, Autor = autorzy.Single(a => a.Nazwa == "Soundgarden"), Okladka = "/Content/Images/placeholder.gif" },
                new Ksiazka { Tytul = "Heart of the Night", Gatunek = gatunki.Single(g => g.Nazwa == "Jazz"), Cena = 8.99M, Autor = autorzy.Single(a => a.Nazwa == "Spyro Gyra"), Okladka = "/Content/Images/placeholder.gif" },
                new Ksiazka { Tytul = "Morning Dance", Gatunek = gatunki.Single(g => g.Nazwa == "Jazz"), Cena = 8.99M, Autor = autorzy.Single(a => a.Nazwa == "Spyro Gyra"), Okladka = "/Content/Images/placeholder.gif" },
                new Ksiazka { Tytul = "In Step", Gatunek = gatunki.Single(g => g.Nazwa == "Blues"), Cena = 8.99M, Autor = autorzy.Single(a => a.Nazwa == "Stevie Ray Vaughan & Double Trouble"), Okladka = "/Content/Images/placeholder.gif" },
                new Ksiazka { Tytul = "Core", Gatunek = gatunki.Single(g => g.Nazwa == "Rock"), Cena = 8.99M, Autor = autorzy.Single(a => a.Nazwa == "Stone Temple Pilots"), Okladka = "/Content/Images/placeholder.gif" },
                new Ksiazka { Tytul = "Mezmerize", Gatunek = gatunki.Single(g => g.Nazwa == "Metal"), Cena = 8.99M, Autor = autorzy.Single(a => a.Nazwa == "System Of A Down"), Okladka = "/Content/Images/placeholder.gif" },
                new Ksiazka { Tytul = "Temple of the Dog", Gatunek = gatunki.Single(g => g.Nazwa == "Alternative"), Cena = 8.99M, Autor = autorzy.Single(a => a.Nazwa == "Temple of the Dog"), Okladka = "/Content/Images/placeholder.gif" },
                new Ksiazka { Tytul = "[1997] Black Light Syndrome", Gatunek = gatunki.Single(g => g.Nazwa == "Rock"), Cena = 8.99M, Autor = autorzy.Single(a => a.Nazwa == "Terry Bozzio, Tony Levin & Steve Stevens"), Okladka = "/Content/Images/placeholder.gif" },
                new Ksiazka { Tytul = "South American Getaway", Gatunek = gatunki.Single(g => g.Nazwa == "Classical"), Cena = 8.99M, Autor = autorzy.Single(a => a.Nazwa == "The 12 Cellists of The Berlin Philharmonic"), Okladka = "/Content/Images/placeholder.gif" },
                new Ksiazka { Tytul = "Live [Disc 1]", Gatunek = gatunki.Single(g => g.Nazwa == "Blues"), Cena = 8.99M, Autor = autorzy.Single(a => a.Nazwa == "The Black Crowes"), Okladka = "/Content/Images/placeholder.gif" },
                new Ksiazka { Tytul = "Live [Disc 2]", Gatunek = gatunki.Single(g => g.Nazwa == "Blues"), Cena = 8.99M, Autor = autorzy.Single(a => a.Nazwa == "The Black Crowes"), Okladka = "/Content/Images/placeholder.gif" },
                new Ksiazka { Tytul = "Beyond Good And Evil", Gatunek = gatunki.Single(g => g.Nazwa == "Rock"), Cena = 8.99M, Autor = autorzy.Single(a => a.Nazwa == "The Cult"), Okladka = "/Content/Images/placeholder.gif" },
                new Ksiazka { Tytul = "The Doors", Gatunek = gatunki.Single(g => g.Nazwa == "Rock"), Cena = 8.99M, Autor = autorzy.Single(a => a.Nazwa == "The Doors"), Okladka = "/Content/Images/placeholder.gif" },
                new Ksiazka { Tytul = "English Renaissance", Gatunek = gatunki.Single(g => g.Nazwa == "Classical"), Cena = 8.99M, Autor = autorzy.Single(a => a.Nazwa == "The King's Singers"), Okladka = "/Content/Images/placeholder.gif" },
                new Ksiazka { Tytul = "The Police Greatest Hits", Gatunek = gatunki.Single(g => g.Nazwa == "Rock"), Cena = 8.99M, Autor = autorzy.Single(a => a.Nazwa == "The Police"), Okladka = "/Content/Images/placeholder.gif" },
                new Ksiazka { Tytul = "Every Kind of Light", Gatunek = gatunki.Single(g => g.Nazwa == "Rock"), Cena = 8.99M, Autor = autorzy.Single(a => a.Nazwa == "The Posies"), Okladka = "/Content/Images/placeholder.gif" },
                new Ksiazka { Tytul = "Hot Rocks, 1964-1971 (Disc 1)", Gatunek = gatunki.Single(g => g.Nazwa == "Rock"), Cena = 8.99M, Autor = autorzy.Single(a => a.Nazwa == "The Rolling Stones"), Okladka = "/Content/Images/placeholder.gif" },
                new Ksiazka { Tytul = "No Security", Gatunek = gatunki.Single(g => g.Nazwa == "Rock"), Cena = 8.99M, Autor = autorzy.Single(a => a.Nazwa == "The Rolling Stones"), Okladka = "/Content/Images/placeholder.gif" },
                new Ksiazka { Tytul = "Voodoo Lounge", Gatunek = gatunki.Single(g => g.Nazwa == "Rock"), Cena = 8.99M, Autor = autorzy.Single(a => a.Nazwa == "The Rolling Stones"), Okladka = "/Content/Images/placeholder.gif" },
                new Ksiazka { Tytul = "My Generation - The Very Best Of The Who", Gatunek = gatunki.Single(g => g.Nazwa == "Rock"), Cena = 8.99M, Autor = autorzy.Single(a => a.Nazwa == "The Who"), Okladka = "/Content/Images/placeholder.gif" },
                new Ksiazka { Tytul = "Serie Sem Limite (Disc 1)", Gatunek = gatunki.Single(g => g.Nazwa == "Latin"), Cena = 8.99M, Autor = autorzy.Single(a => a.Nazwa == "Tim Maia"), Okladka = "/Content/Images/placeholder.gif" },
                new Ksiazka { Tytul = "Serie Sem Limite (Disc 2)", Gatunek = gatunki.Single(g => g.Nazwa == "Latin"), Cena = 8.99M, Autor = autorzy.Single(a => a.Nazwa == "Tim Maia"), Okladka = "/Content/Images/placeholder.gif" },
                new Ksiazka { Tytul = "Bach: Toccata & Fugue in D Minor", Gatunek = gatunki.Single(g => g.Nazwa == "Classical"), Cena = 8.99M, Autor = autorzy.Single(a => a.Nazwa == "Ton Koopman"), Okladka = "/Content/Images/placeholder.gif" },
                new Ksiazka { Tytul = "Achtung Baby", Gatunek = gatunki.Single(g => g.Nazwa == "Rock"), Cena = 8.99M, Autor = autorzy.Single(a => a.Nazwa == "U2"), Okladka = "/Content/Images/placeholder.gif" },
                new Ksiazka { Tytul = "B-Sides 1980-1990", Gatunek = gatunki.Single(g => g.Nazwa == "Rock"), Cena = 8.99M, Autor = autorzy.Single(a => a.Nazwa == "U2"), Okladka = "/Content/Images/placeholder.gif" },
                new Ksiazka { Tytul = "How To Dismantle An Atomic Bomb", Gatunek = gatunki.Single(g => g.Nazwa == "Rock"), Cena = 8.99M, Autor = autorzy.Single(a => a.Nazwa == "U2"), Okladka = "/Content/Images/placeholder.gif" },
                new Ksiazka { Tytul = "Pop", Gatunek = gatunki.Single(g => g.Nazwa == "Rock"), Cena = 8.99M, Autor = autorzy.Single(a => a.Nazwa == "U2"), Okladka = "/Content/Images/placeholder.gif" },
                new Ksiazka { Tytul = "Rattle And Hum", Gatunek = gatunki.Single(g => g.Nazwa == "Rock"), Cena = 8.99M, Autor = autorzy.Single(a => a.Nazwa == "U2"), Okladka = "/Content/Images/placeholder.gif" },
                new Ksiazka { Tytul = "The Best Of 1980-1990", Gatunek = gatunki.Single(g => g.Nazwa == "Rock"), Cena = 8.99M, Autor = autorzy.Single(a => a.Nazwa == "U2"), Okladka = "/Content/Images/placeholder.gif" },
                new Ksiazka { Tytul = "War", Gatunek = gatunki.Single(g => g.Nazwa == "Rock"), Cena = 8.99M, Autor = autorzy.Single(a => a.Nazwa == "U2"), Okladka = "/Content/Images/placeholder.gif" },
                new Ksiazka { Tytul = "Zooropa", Gatunek = gatunki.Single(g => g.Nazwa == "Rock"), Cena = 8.99M, Autor = autorzy.Single(a => a.Nazwa == "U2"), Okladka = "/Content/Images/placeholder.gif" },
                new Ksiazka { Tytul = "UB40 The Best Of - Volume Two [UK]", Gatunek = gatunki.Single(g => g.Nazwa == "Reggae"), Cena = 8.99M, Autor = autorzy.Single(a => a.Nazwa == "UB40"), Okladka = "/Content/Images/placeholder.gif" },
                new Ksiazka { Tytul = "Diver Down", Gatunek = gatunki.Single(g => g.Nazwa == "Rock"), Cena = 8.99M, Autor = autorzy.Single(a => a.Nazwa == "Van Halen"), Okladka = "/Content/Images/placeholder.gif" },
                new Ksiazka { Tytul = "The Best Of Van Halen, Vol. I", Gatunek = gatunki.Single(g => g.Nazwa == "Rock"), Cena = 8.99M, Autor = autorzy.Single(a => a.Nazwa == "Van Halen"), Okladka = "/Content/Images/placeholder.gif" },
                new Ksiazka { Tytul = "Van Halen III", Gatunek = gatunki.Single(g => g.Nazwa == "Rock"), Cena = 8.99M, Autor = autorzy.Single(a => a.Nazwa == "Van Halen"), Okladka = "/Content/Images/placeholder.gif" },
                new Ksiazka { Tytul = "Van Halen", Gatunek = gatunki.Single(g => g.Nazwa == "Rock"), Cena = 8.99M, Autor = autorzy.Single(a => a.Nazwa == "Van Halen"), Okladka = "/Content/Images/placeholder.gif" },
                new Ksiazka { Tytul = "Axé Bahia 2001", Gatunek = gatunki.Single(g => g.Nazwa == "Pop"), Cena = 8.99M, Autor = autorzy.Single(a => a.Nazwa == "Various Artists"), Okladka = "/Content/Images/placeholder.gif" },
                new Ksiazka { Tytul = "Sambas De Enredo 2001", Gatunek = gatunki.Single(g => g.Nazwa == "Latin"), Cena = 8.99M, Autor = autorzy.Single(a => a.Nazwa == "Various Artists"), Okladka = "/Content/Images/placeholder.gif" },
                new Ksiazka { Tytul = "Vozes do MPB", Gatunek = gatunki.Single(g => g.Nazwa == "Latin"), Cena = 8.99M, Autor = autorzy.Single(a => a.Nazwa == "Various Artists"), Okladka = "/Content/Images/placeholder.gif" },
                new Ksiazka { Tytul = "Contraband", Gatunek = gatunki.Single(g => g.Nazwa == "Rock"), Cena = 8.99M, Autor = autorzy.Single(a => a.Nazwa == "Velvet Revolver"), Okladka = "/Content/Images/placeholder.gif" },
                new Ksiazka { Tytul = "Vinicius De Moraes", Gatunek = gatunki.Single(g => g.Nazwa == "Latin"), Cena = 8.99M, Autor = autorzy.Single(a => a.Nazwa == "Vinícius De Moraes"), Okladka = "/Content/Images/placeholder.gif" },
                new Ksiazka { Tytul = "Bach: Goldberg Variations", Gatunek = gatunki.Single(g => g.Nazwa == "Classical"), Cena = 8.99M, Autor = autorzy.Single(a => a.Nazwa == "Wilhelm Kempff"), Okladka = "/Content/Images/placeholder.gif" },
                new Ksiazka { Tytul = "Bartok: Violin & Viola Concertos", Gatunek = gatunki.Single(g => g.Nazwa == "Classical"), Cena = 8.99M, Autor = autorzy.Single(a => a.Nazwa == "Yehudi Menuhin"), Okladka = "/Content/Images/placeholder.gif" },
                new Ksiazka { Tytul = "Bach: The Cello Suites", Gatunek = gatunki.Single(g => g.Nazwa == "Classical"), Cena = 8.99M, Autor = autorzy.Single(a => a.Nazwa == "Yo-Yo Ma"), Okladka = "/Content/Images/placeholder.gif" },
                new Ksiazka { Tytul = "Ao Vivo [IMPORT]", Gatunek = gatunki.Single(g => g.Nazwa == "Latin"), Cena = 8.99M, Autor = autorzy.Single(a => a.Nazwa == "Zeca Pagodinho"), Okladka = "/Content/Images/placeholder.gif" },
            }.ForEach(a => context.Ksiazki.Add(a));
        }
    }
}